os:
    - osx
    - linux

env:
    - CXX_STANDARD=c++98
    - CXX_STANDARD=c++0x

before_install:
    - echo OS is ${TRAVIS_OS_NAME}
    - wget https://github.com/ned14/boost-release/archive/master.tar.gz
    - tar xf master.tar.gz
    - mv boost-release-master $HOME/boost-local
    - BOOST="$HOME/boost-local"
    - mkdir $BOOST/libs/dll
    - cp -rf ../Boost.DLL/* $BOOST/libs/dll/
    - cd $BOOST
    - ./bootstrap.sh

script:
    - echo OS is ${TRAVIS_OS_NAME}
    - if [ "$CCFLAGS" != "" ]; then FLAGS="cxxflags=\"$CCFLAGS\" linkflags=\"$LINKFLAGS\""; else FLAGS=""; fi
    - cd $BOOST/libs/dll/test/
    - ../../../b2 cxxflags=\"-std=$CXX_STANDARD\"
