language: cpp

compiler:
    - gcc
    - clang

before_install:
    - wget https://github.com/ned14/boost-release/archive/master.tar.gz
    - tar xf master.tar.gz
    - mv boost-release-master $HOME/boost-local
    - BOOST="$HOME/boost-local"
    - cd $BOOST/libs
    - git clone https://github.com/apolukhin/Boost.DLL dll
    - cd $BOOST
    - ./bootstrap.sh
    - ./b2 headers


script:
    - if [ "$CCFLAGS" != "" ]; then FLAGS="cxxflags=\"$CCFLAGS\" linkflags=\"$LINKFLAGS\""; else FLAGS=""; fi
    - cd $BOOST/libs/dll/test/
    - ../../../b2 toolset=$CC $FLAGS
