language: cpp

compiler:
    - gcc
    - clang

before_install:
    - wget https://github.com/ned14/boost-release/archive/master.tar.gz
    - tar xf master.tar.gz
    - mv boost-release-master $HOME/boost-local
    - BOOST="$HOME/boost-local"
    - PROJECTPATH="./"
    - ln -s $PROJECTPATH $BOOST/libs/dll
    - cd $BOOST
    - ./bootstrap.sh
    - ./b2 headers


script:
    - if [ "$CCFLAGS" != "" ]; then FLAGS="cxxflags=\"$CCFLAGS\" linkflags=\"$LINKFLAGS\""; else FLAGS=""; fi
    - if [ $GCOV -eq 1 ]; then FLAGS="$FLAGS --test-all"; fi
    - cd $BOOST/libs/dll/test
    - eval "../../../b2 $DEBUGBUILD toolset=$CC $FLAGS"
